# Generated by Django 4.1.1 on 2022-09-16 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_ciudad_usuario_empresa_usuario_grupo_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viudo(a)'), ('U', 'Union Libre')], default='S', max_length=1, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefonos', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_IESS', models.DateField(blank=True, null=True)),
                ('tipo_Contrato', models.CharField(blank=True, choices=[('CI', 'Contrato indefinido'), ('CT', 'Contarto temporal'), ('CP', 'Contrato en prácticas')], default='CI', max_length=2, null=True)),
                ('fecha_Ingreso', models.DateField(blank=True, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='fichaPersonal/empleados')),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ciudad')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pais')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.provincia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ('-cedula', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('telefonos', models.CharField(blank=True, max_length=50, null=True)),
                ('parentesco', models.CharField(blank=True, choices=[('M', 'Madre'), ('P', 'Padre'), ('H', 'Hermano(a)'), ('A', 'Abuelo(a)'), ('T', 'Tio(a)'), ('P', 'Primo(a)'), ('S', 'Sobrino(a)'), ('C', 'Cuñado(a)'), ('Pd', 'Padrastro'), ('Md', 'Madrastra'), ('Co', 'Conyuge'), ('Hi', 'Hijo(a)'), ('O', 'Otros')], default='M', max_length=2, null=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ContactoEmergencia',
                'verbose_name_plural': 'ContactosEmergencias',
                'ordering': ('-cedula', 'nombres'),
            },
        ),
    ]
