# Generated by Django 4.1.1 on 2022-09-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoemergencias',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ficha_personal.empleado'),
        ),
    ]
