# Generated by Django 4.1.1 on 2022-09-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0003_cargo_empleado_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='fecha_eliminacion',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cargo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
