# Generated by Django 4.1.1 on 2022-09-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0005_departamento_empleado_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ('id',), 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('id',), 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
