# Generated by Django 4.1.1 on 2022-09-17 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha_personal', '0006_alter_cargo_options_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactoemergencias',
            options={'ordering': ('id',), 'verbose_name': 'ContactoEmergencia', 'verbose_name_plural': 'ContactosEmergencias'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ('id',), 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.CreateModel(
            name='InfoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('fecha_Inicio', models.DateField(blank=True, null=True)),
                ('fecha_Fin', models.DateField(blank=True, null=True)),
                ('institucion', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ficha_personal.empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InfoAcademica',
                'verbose_name_plural': 'InfoAcademicas',
                'ordering': ('id',),
            },
        ),
    ]
