# Generated by Django 4.1.1 on 2022-09-17 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha_personal', '0007_alter_contactoemergencias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoemergencias',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fichaPersonal/empleados'),
        ),
        migrations.AlterField(
            model_name='infoacademica',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.empleado'),
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='fichaPersonal/capacitaciones')),
                ('fecha_Inicio', models.DateField(blank=True, null=True)),
                ('fecha_Fin', models.DateField(blank=True, null=True)),
                ('duracion', models.CharField(max_length=10, unique=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capacitacion',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ('id',),
            },
        ),
    ]
