# Generated by Django 4.1.1 on 2022-09-17 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha_personal', '0008_alter_contactoemergencias_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('sueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Sueldo')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sueldo',
                'verbose_name_plural': 'Sueldos',
                'ordering': ('id',),
            },
        ),
    ]
