# Generated by Django 4.1.1 on 2022-09-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0011_remove_capacitaciones_fecha_eliminacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoemergencias',
            old_name='empleado',
            new_name='empleado_id',
        ),
    ]
