# Generated by Django 4.1.1 on 2022-09-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0012_rename_empleado_contactoemergencias_empleado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoemergencias',
            old_name='empleado_id',
            new_name='empleado',
        ),
    ]
