# Generated by Django 4.1.1 on 2022-09-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0014_rename_nombres_contactoemergencias_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitaciones',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='contactoemergencias',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='infoacademica',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='sueldo',
            name='empleado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='capacitaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.capacitaciones'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contacEmergencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.contactoemergencias'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='infoAcademica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.infoacademica'),
        ),
    ]
