# Generated by Django 4.1.1 on 2022-09-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0015_remove_capacitaciones_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='capacitaciones',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='contacEmergencia',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='infoAcademica',
        ),
        migrations.AddField(
            model_name='capacitaciones',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.empleado'),
        ),
        migrations.AddField(
            model_name='contactoemergencias',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.empleado'),
        ),
        migrations.AddField(
            model_name='infoacademica',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.empleado'),
        ),
        migrations.AddField(
            model_name='sueldo',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ficha_personal.empleado'),
        ),
    ]
