# Generated by Django 4.1.1 on 2022-09-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0016_remove_empleado_capacitaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciones',
            name='duracion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='infoacademica',
            name='institucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
