# Generated by Django 4.1.1 on 2022-09-25 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0017_alter_capacitaciones_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoemergencias',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='ficha_personal.empleado'),
        ),
        migrations.AlterField(
            model_name='contactoemergencias',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('M', 'Madre'), ('P', 'Padre'), ('H', 'Hermano(a)'), ('A', 'Abuelo(a)'), ('T', 'Tio(a)'), ('Pr', 'Primo(a)'), ('S', 'Sobrino(a)'), ('C', 'Cuñado(a)'), ('Pd', 'Padrastro'), ('Md', 'Madrastra'), ('Co', 'Conyuge'), ('Hi', 'Hijo(a)'), ('O', 'Otros')], default='M', max_length=2, null=True),
        ),
    ]
