# Generated by Django 4.1.1 on 2022-09-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0018_alter_contactoemergencias_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactoemergencias',
            name='parentesco',
        ),
    ]
