# Generated by Django 4.1.1 on 2022-10-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0020_contactoemergencias_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
