# Generated by Django 4.1.1 on 2022-10-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_personal', '0021_alter_empleado_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
